In [2]:
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

In [3]:
#Q1. Difference in data type of variables list_ and array_list

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

print("Data type of list_: ", type(list_))
print("Data type of array_list: ", type(array_list))

Data type of list_:  <class 'list'>
Data type of array_list:  <class 'numpy.ndarray'>


In [4]:
#Q2. Print the data type of each element of both variables



import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

print("Data type of each element in list_: ")
for elem in list_:
    print(type(elem))

print("\nData type of each element in array_list: ")
for elem in array_list:
    print(elem.dtype)  # or type(elem) for Python type

Data type of each element in list_: 
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each element in array_list: 
<U1
<U1
<U1
<U1
<U1


In [5]:
array_list = np.array(object = list_, dtype = int)

In [6]:
#Q3. Difference in data type of elements with dtype=int
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

print("Data type of each element in list_: ")
for elem in list_:
    print(type(elem))

print("\nData type of each element in array_list: ")
for elem in array_list:
    print(type(elem))

Data type of each element in list_: 
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each element in array_list: 
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [7]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [8]:
#Q4. Characteristics of num_array
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# (i) Shape
print("Shape of num_array: ", num_array.shape)

# (ii) Size
print("Size of num_array: ", num_array.size)

Shape of num_array:  (2, 3)
Size of num_array:  6


In [9]:
#Q5. Create a 3 × 3 NumPy array of zeros
import numpy as np

zeros_array = np.zeros((3, 3))

print("Array of zeros:")
print(zeros_array)
print("\nShape of zeros_array: ", zeros_array.shape)
print("\nSize of zeros_array: ", zeros_array.size)

Array of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Shape of zeros_array:  (3, 3)

Size of zeros_array:  9
